import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'AI运营',
      items: ['ai-analytics', 'ai-analytics-updates'],
    },
    {
      type: 'category',
      label: '浏览器插件',
      items: ['browser-plugin', 'browser-plugin-updates'],
    },
    {
      type: 'category',
      label: 'AI客服',
      items: ['customer-service', 'ai-customer-service-updates'],
    },
    {
      type: 'category',
      label: 'AI Agent',
      items: [
        {
          type: 'autogenerated',
          dirName: 'agntc',
        },
      ],
    },
    {
      type: 'category',
      label: 'cclee-docusaurus-theme',
      items: ['cclee-docusaurus-theme'],
    },
    {
      type: 'category',
      label: 'WordPress 生态',
      items: ['cclee-theme'],
    },
    {
      type: 'category',
      label: 'CCLEE Toolkit',
      items: ['cclee-toolkit', 'cclee-toolkit-image-alt', 'cclee-toolkit-seo', 'cclee-toolkit-woo'],
    },
    {
      type: 'category',
      label: 'CCLEE B2B',
      items: [
        'cclee-b2b-general',
        'cclee-b2b-product',
        'cclee-b2b-pricing',
        'cclee-b2b-registration',
        'cclee-b2b-rfq',
        'cclee-b2b-ai',
        'cclee-b2b-updates',
        'cclee-b2b-pdf',
      ],
    },
    {
      type: 'category',
      label: '跨境铺货助手',
      items: ['ai-product-listing'],
    },
    {
      type: 'category',
      label: 'WooCommerce 物流',
      items: ['cclee-shipping', 'fedex-registration'],
    },
    {
      type: 'category',
      label: '任务栈',
      items: ['task-stack'],
    },
  ],
};

export default sidebars;
